# Generated by Django 3.0.7 on 2020-06-18 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField(max_length=2000)),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 18, 19, 26, 32, 506781))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Adduser')),
            ],
        ),
    ]
