# Generated by Django 3.0.7 on 2020-06-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 18, 20, 8, 32, 961635)),
        ),
    ]
