# Generated by Django 3.0.7 on 2020-06-21 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200618_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 9, 15, 29, 203412)),
        ),
    ]
