# Generated by Django 3.1.4 on 2020-12-15 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200621_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
